# Generated by Django 5.1.7 on 2025-03-21 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('birth_date', models.DateField()),
                ('age', models.IntegerField()),
                ('confirmation_code', models.CharField(blank=True, max_length=6)),
                ('marital_status', models.CharField(choices=[('Never Married', 'Never Married'), ('Divorced', 'Divorced')], max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('living_status', models.CharField(max_length=50)),
                ('us_citizen', models.BooleanField(default=False)),
                ('visa_status', models.CharField(blank=True, max_length=10)),
                ('parents_aware', models.BooleanField(default=False)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('birth_time', models.TimeField()),
                ('education', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('food_preference', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('siblings', models.TextField(blank=True)),
                ('father_name', models.CharField(max_length=100)),
                ('father_native', models.CharField(max_length=100)),
                ('father_phone', models.CharField(max_length=15)),
                ('father_location', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_siblings', models.TextField()),
                ('father_maternal_family', models.TextField()),
                ('grandfather_name', models.CharField(max_length=100)),
                ('grandmother_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_father_name', models.CharField(max_length=100)),
                ('mother_maternal_family', models.TextField()),
                ('full_body_image', models.ImageField(upload_to='profiles/')),
                ('half_body_image', models.ImageField(upload_to='profiles/')),
                ('extra_image1', models.ImageField(blank=True, upload_to='profiles/')),
                ('extra_image2', models.ImageField(blank=True, upload_to='profiles/')),
                ('extra_image3', models.ImageField(blank=True, upload_to='profiles/')),
                ('referred_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
