# Generated by Django 5.1.7 on 2025-03-21 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='father_maternal_family',
            new_name='father_maternal',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='father_phone',
            new_name='father_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='mother_maternal_family',
            new_name='mother_maternal',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='food_preference',
            field=models.CharField(choices=[('V', 'Veg'), ('N', 'Non-Veg')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='living_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('N', 'Never Been Married'), ('D', 'Divorced')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='siblings',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visa_status',
            field=models.CharField(blank=True, choices=[('F1', 'F1'), ('H1B', 'H1B'), ('Other', 'Other')], max_length=10),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
