# Generated by Django 5.1.7 on 2025-03-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_father_maternal_family_profile_father_maternal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='about_yourself',
        ),
    ]
