# Generated by Django 5.1.7 on 2025-03-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_description_profile_about_yourself'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='living_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referred_from',
        ),
    ]
