# Generated by Django 5.1.7 on 2025-03-22 03:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_about_yourself_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='native',
            field=models.CharField(default='Default Native', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Dummy Event Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_yourself',
            field=models.TextField(default='No information provided'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_time',
            field=models.CharField(default='12:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Dummy City', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='confirmation_code',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_address',
            field=models.CharField(default='Dummy Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(default='Dummy Education', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='extra_image1',
            field=models.ImageField(blank=True, default='profiles/default_image.jpg', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='extra_image2',
            field=models.ImageField(blank=True, default='profiles/default_image.jpg', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='extra_image3',
            field=models.ImageField(blank=True, default='profiles/default_image.jpg', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_location',
            field=models.CharField(default='Dummy Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_maternal',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(default='Dummy Father Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_native',
            field=models.CharField(default='Dummy Father Native', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_number',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_occupation',
            field=models.CharField(default='Dummy Occupation', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_siblings',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='food_preference',
            field=models.CharField(choices=[('V', 'Veg'), ('N', 'Non-Veg')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_body_image',
            field=models.ImageField(default='profiles/default_full_body.jpg', upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grandfather_name',
            field=models.CharField(default='Dummy Grandfather Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grandmother_name',
            field=models.CharField(default='Dummy Grandmother Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='half_body_image',
            field=models.ImageField(default='profiles/default_half_body.jpg', upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('N', 'Never Been Married'), ('D', 'Divorced')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_father_name',
            field=models.CharField(default="Dummy Mother's Father Name", max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_maternal',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_name',
            field=models.CharField(default='Dummy Mother Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Dummy Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='Dummy Occupation', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referred_by',
            field=models.ForeignKey(default=None, limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='siblings',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Dummy State', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='visa_status',
            field=models.CharField(choices=[('F1', 'F1'), ('H1B', 'H1B'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.event'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
