# Generated by Django 5.1.7 on 2025-03-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_native_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Enter City', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_address',
            field=models.CharField(default='Enter Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(default='Enter Education', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_location',
            field=models.CharField(default='Enter Location', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(default='Enter Father Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_native',
            field=models.CharField(default='Enter Father Native', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_occupation',
            field=models.CharField(default='Enter Occupation', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grandfather_name',
            field=models.CharField(default='Enter Grandfather Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grandmother_name',
            field=models.CharField(default='Enter Grandmother Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_father_name',
            field=models.CharField(default="Enter Mother's Father Name", max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_name',
            field=models.CharField(default='Enter Mother Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Enter Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='native',
            field=models.CharField(default='Enter Native', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='Enter Occupation', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Enter State', max_length=100),
        ),
    ]
